### ISSUE TITLE
Support for Lambda Aliases as part of deployment specification

### ISSUE THREAD

**Issue by kiernana** [alexa-labs/ask-cli#31]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Support for Lambda Aliases as part of deployment specification

## Expected Behavior

Either by pre-defined specification constraint or by user determination of Aliases, support for lambda aliases in the deployment management elements would aid in the standardisation & simplification of process.

**Comment by RonWang** [comment]
Hey @kiernana 

First thank you for your feature request.
The good news is that: [**ask-cli-x**](https://www.npmjs.com/package/ask-cli-x) is exactly designed to solve your need on AWS Lambda related configurations, because it's using AWS CloudFormation to deploy your Lambda functions. You will be able to modify the skill stack template following the [AWS instruction](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html) to support the aliases deployment.

More specifically, assuming you have an AlexaSkillFunction as your Lambda function, you will want to add:
```
AlexaSkillFunctionAlias:
  Type: AWS::Lambda::Alias
  Properties: 
    FunctionName: 
      Ref: AlexaSkillFunctioin
    FunctionVersion: // using "LATEST" or the version #
    Name: // Specify the purpose of this alias
```
Let me know if this solves your question!

Thanks,
Ron

**Comment by RonWang** [comment]
Close this issue as no further response, please feel free to provide more details if you have further questions!

**Comment by kiernana** [comment]
Thanks Ron  !
