### ISSUE TITLE
Support for Lambda Environment Variables in the ask configuration.

### ISSUE THREAD

**Issue by kiernana** [alexa-labs/ask-cli#32]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Support for Lambda Environment Variables would provided an additional level of flexibility and simplicity in both the deployment process and operational lifecycle, given the its typical to have different parameter values between development and production environments.

**Comment by RonWang** [comment]
Hey @kiernana 

First thank you for your feature request.
The good news is that: [**ask-cli-x**](https://www.npmjs.com/package/ask-cli-x) is exactly designed to solve your need on AWS Lambda related configurations, because it's using AWS CloudFormation to deploy your Lambda functions. You will be able to modify the skill stack template following the [AWS instruction](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-environment.html) to support the aliases deployment.

More specifically, assuming AlexaSkillFunction is your Lambda function, you will want to add the `Environment` property:
```
AlexaSkillFunction:
  Type: AWS::Lambda::Function
  Properties: 
    ...
    Environment: 
      Variables:
        Key: Value // you can set the EnvVar for your Lambda here, and the next "askx deploy" will put it into effect for your Lambda
    ...
```
Let me know if this solves your question!

Thanks,
Ron

**Comment by rox786** [comment]
Hey @kiernana
Please update your email, I am receiving mails for you activity

**Comment by RonWang** [comment]
Close this issue as no further response, please feel free to provide more details if you have further questions!

**Comment by kiernana** [comment]
Thanks Ron !
