### ISSUE TITLE
Default Hello World Skill template not working

### ISSUE THREAD

**Issue by shifatul-i** [alexa-labs/ask-cli#59]
I created a skill using the template
![image](https://user-images.githubusercontent.com/3328263/76051496-da574a00-5f1f-11ea-813b-5be19d284a71.png)

Then I went to Dev site to test it
![image](https://user-images.githubusercontent.com/3328263/76051569-15f21400-5f20-11ea-9b9a-46b6f422bc06.png)

As you can see its not working
Here are the logs from cloudwatch
![image](https://user-images.githubusercontent.com/3328263/76051607-302bf200-5f20-11ea-945a-a813baf75be3.png)

**Comment by RonWang** [comment]
Hi @shifatul-i ,
After some deep dive after reproducing your issue, it turns out this issue has been mentioned in #39 . 

For now to unblock yourself, please use the solution proposed in the thread (provided by @desiderataaus ), which is to run the following command to fix the Powershell bug:
```
Install-Module Microsoft.PowerShell.Archive -MinimumVersion 1.2.3.0 -Repository PSGallery -Force
```

After fixing Powershell, please re-run the `askx deploy` again to let CLI re-build your code, which will compress your code correctly this time, and finally upload it to Lambda. Lambda should work now.

We will also put it into our FAQ doc for this specific issue.

Thanks,
Ron

**Comment by danieldhz** [comment]
Hi There,
I faced similar issue despite running your recommended code on PowerShell. Essentially, when I build a skill on dev console, i don't get an error. However, once I build the same skill and launch it via cli i get packages error (i.e. 'ServiceClientFactory' object has no attribute 'get_timer_management_service'). I'd assume its because my SDK are not updated. However, now that I checked my ask-sdk == 1.13.0 & ask-cli ==2.12.0 which I believe both are the latest versions.
